apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: onlineeventbooking-afsah
data:
  # PostgreSQL User Service
  POSTGRES_USER_USER: "postgres_user"
  POSTGRES_DB_USER: "event_booking"

  # PostgreSQL Event Service
  POSTGRES_USER_EVENT: "postgres_event"
  POSTGRES_DB_EVENT: "Events"

  # MongoDB Connection URIs
  MONGO_URI_BOOKING: "mongodb://mongo-booking-db:27017/BookingDB"
  MONGO_URI_NOTIFICATION: "mongodb://mongo-notification-db:27017/notifications_db"

  # RabbitMQ
  RABBITMQ_URL: "amqp://guest:guest@rabbitmq:5672/"

  # API URLs for Service-to-Service Communication
  EVENT_SERVICE_URL: "http://event-service:80"
  USER_SERVICE_URL: "http://user-service:80"
  BOOKING_SERVICE_URL: "http://booking-service:80"
  NOTIFICATION_SERVICE_URL: "http://notification-service:80"

  # Email Configuration
  EMAIL_HOST: "smtp.gmail.com"
  EMAIL_PORT: "587"
