apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service-deployment
  namespace: onlineeventbooking-afsah
spec:
  replicas: 2
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
      - name: notification-service
        image: 22i1046/notification-service:latest
        ports:
        - containerPort: 5002
        envFrom:
        - configMapRef:
            name: app-config
        - secretRef:
            name: app-secrets
        env:
        - name: MONGO_URI_NOTIFICATION
          value: "mongodb://mongo-notification-db:27017/$(MONGO_DB_NOTIFICATION)"
        - name: RABBITMQ_URL
          value: "amqp://$(RABBITMQ_USER):$(RABBITMQ_PASSWORD)@rabbitmq:5672/"
        - name: EMAIL_HOST
          value: "$(EMAIL_HOST)"
        - name: EMAIL_PORT
          value: "$(EMAIL_PORT)"
        - name: EMAIL_USERNAME
          value: "$(EMAIL_USERNAME)"
        - name: EMAIL_PASSWORD
          valueFrom:
              secretKeyRef:
                name: app-secrets
                key: EMAIL_PASSWORD
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: onlineeventbooking-afsah
spec:
  selector:
    app: notification-service
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5002
  type: ClusterIP
