apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-service-deployment
  namespace: onlineeventbooking-afsah
spec:
  replicas: 2
  selector:
    matchLabels:
      app: event-service
  template:
    metadata:
      labels:
        app: event-service
    spec:
      containers:
      - name: event-service
        image: 22i1046/event-service:latest
        ports:
        - containerPort: 8000
        envFrom:
        - configMapRef:
            name: app-config
        - secretRef:
            name: app-secrets
        env:
        - name: DATABASE_URL
          value: "postgresql://$(POSTGRES_USER_EVENT):$(POSTGRES_PASSWORD_EVENT)@postgres-event:5432/$(POSTGRES_DB_EVENT)"
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"

---
apiVersion: v1
kind: Service
metadata:
  name: event-service
  namespace: onlineeventbooking-afsah
spec:
  selector:
    app: event-service
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
  type: ClusterIP
