apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: onlineeventbooking-afsah
type: Opaque
data:
  # PostgreSQL User Service Credentials
  POSTGRES_USER_USER: "cG9zdGdyZXNfdXNlcg=="      # Base64 of "postgres_user"
  POSTGRES_PASSWORD_USER: "MTIzNA=="              # Base64 of "1234"
  POSTGRES_DB_USER: "ZXZlbnRfYm9va2luZw=="        # Base64 of "event_booking"

  # PostgreSQL Event Service Credentials
  POSTGRES_USER_EVENT: "cG9zdGdyZXNfZXZlbnQ="     # Base64 of "postgres_event"
  POSTGRES_PASSWORD_EVENT: "MTIzNA=="            # Base64 of "1234"
  POSTGRES_DB_EVENT: "RXZlbnRz"                  # Base64 of "Events"
  
  # RabbitMQ Credentials
  RABBITMQ_USER: "Z3Vlc3Q="        # base64 of "guest"
  RABBITMQ_PASSWORD: "Z3Vlc3Q="        # base64 of "guest"
  
  # Email Credentials
  EMAIL_USERNAME: "YWZzYWhhcmVlYjc4NjJAZ21haWwuY29t" # Base64 of "afsahareeb7862@gmail.com"
  EMAIL_PASSWORD: "ZGhteSBnZGlvIGl1c3IgdXR5cA=="  # Base64 of "dhmy gdio iusr utyp"
